### ISSUE TITLE
Problem with understanding logic.

### ISSUE THREAD

**Issue by mariuszmalek** [CympleTech/ESSE#16]
Can you explain why the Rust is in the same file as Flutter? I am trying to understand all the logic to be able to install this locally. I have problems running the application in XCode. I only get splash screen for a few seconds and kick me out.

**Comment by mariuszmalek** [comment]
When I run `flutter run` (IOS):

`Error output from CocoaPods:
↳

    [!] Automatically assigning platform `iOS` with version `11.0` on target `Runner` because no platform was specified. Please
    specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require':
    dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): tried:
    '/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'arm64',
    need 'x86_64')), '/usr/lib/ffi_c.bundle' (no such file) - /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle
    (LoadError)`

**Comment by sunhuachuang** [comment]
Sure. 
Rust and Dart were in different repos before, but I think they are related and changed together, so they are in the same directory.

I think crash when after few seconds, maybe due to the rust code panic. (when started, Rust code will auto starting tokio runtime  for network and others). Does the app have network permission ?

I don't have a macOS around now (on vacation :) ), can you tell me the iOS version?

**Comment by mariuszmalek** [comment]
So is it possible to separate Flutter and Rust? I have the permissions set, but it is rather a problem related to the IOS version. I have 15 versions of IOS.

**Comment by mariuszmalek** [comment]
I have a solution. For those who have M1.

1.
Run this command to find all CocoaPods Components `gem list --local | grep cocoapods` Then for each version/component you want to uninstall each one.

```
2.
sudo gem uninstall cocoapods
sudo gem uninstall cocoapods-core
sudo gem uninstall cocoapods-downloader
sudo gem uninstall cocoapods-deintegrate
```

3.
Once each dependency is uninstalled - install the ARM version of the ffi package: `sudo arch -x86_64 gem install ffi`

4.
Install the rest of the CocoaPods using the ARM version `sudo arch -x86_64 gem install cocoapods
`

**Comment by sunhuachuang** [comment]
> I have a solution. For those who have M1.

Cool :+1: 

> So is it possible to separate Flutter and Rust?

Yes, easier to implement. Rust code only in `/src`, `/Cargo.toml`, others all Flutter.

Some reference maybe can find at [cargo-lipo](https://github.com/TimNN/cargo-lipo). It feels like the problem comes from the architecture ?

**Comment by mariuszmalek** [comment]
@sunhuachuang, I got a new error:

`building for iOS
Simulator, but linking in object file built for iOS, for architecture arm64`

Can you help me with that?

PS. Regarding the architecture itself, I asked questions in order to better understand everything.

**Comment by sunhuachuang** [comment]
I think it is ready to close, if any questions, please let me know.
