### ISSUE TITLE
Can you help me compile windows 64?

### ISSUE THREAD

**Issue by xp12047** [CympleTech/ESSE#22]
I don't know how to compile windows files even though I read your tutorial and failed a few times.  The binary link to the documentation is also not available for download.  thanks

**Comment by sunhuachuang** [comment]
Hi, sorry for that, and I don't have a windows device to test now, and what is the error when you build it?

**Comment by xp12047** [comment]
> 您好，抱歉，我现在没有要测试的 Windows 设备，您构建它时出现什么错误？

Sorry, I forgot to take a screenshot.  I remember when I was compiling, the windows system would prompt that the package of c was missing. I'm still not sure where the packages are, but when I searched the Internet, I saw a few similar ones. It's very big for me.  The notebook will be more difficult to run.  But it's okay, I won't give up.  I'll try to compile it when I get a chance.  I love this project.  thanks
