### ISSUE TITLE
** BUILD FAILED **

### ISSUE THREAD

**Issue by gionlime** [CympleTech/ESSE#23]
jeek@jeekdeMacBook-Pro ESSE % flutter build macos

💪 Building with sound null safety 💪

Running pod install...                                           2,429ms
ld: warning: ignoring file /Users/jeek/web3/ESSE/core/macos/share/libesse.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_start", referenced from:
      _$s9esse_core14EsseCorePluginC6handle_6resultySo17FlutterMethodCallC_yypSgctFyycfU_TA in EsseCorePlugin.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
** BUILD FAILED **

**Comment by sunhuachuang** [comment]
Thx, and I found that it is failure to compile on mac, because the version of the dependent library is upgraded, and I am working on upgrade and fixed the version.

**Comment by gionlime** [comment]
> Thx, and I found that it is failure to compile on mac, because the version of the dependent library is upgraded, and I am working on upgrade and fixed the version.

Tankyou very much!

**Comment by sunhuachuang** [comment]
Hi gionlime, maybe you can try again, I fixed all error in my macOS device.

**Comment by sunhuachuang** [comment]
Feel free to reopen if still not work.
