### ISSUE TITLE
error[E0599]: no method named `global_processor_info` found for struct `sysinfo::System` in the current scope

### ISSUE THREAD

**Issue by gionlime** [CympleTech/ESSE#36]
<img width="899" alt="截屏2022-11-29 12 19 37" src="https://user-images.githubusercontent.com/91245043/204438068-a51bc498-e631-4361-9fae-dd6124b4be7f.png">

error[E0599]: no method named `global_processor_info` found for struct `sysinfo::System` in the current scope
  --> src/utils/device_status.rs:10:17
   |
10 |     let cpu = s.global_processor_info().cpu_usage();
   |                 ^^^^^^^^^^^^^^^^^^^^^ method not found in `sysinfo::System`

warning: unused import: `web3::signing::Key`
  --> src/account.rs:13:5
   |
13 | use web3::signing::Key;
   |     ^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused import: `signing::Key`
  --> src/apps/wallet/rpc.rs:12:5
   |
12 |     signing::Key,
   |     ^^^^^^^^^^^^

Some errors have detailed explanations: E0271, E0432, E0599.
For more information about an error, try `rustc --explain E0271`.
warning: `esse` (lib) generated 2 warnings
error: could not compile `esse` due to 7 previous errors; 2 warnings emitted
Rust: Macos release build ok!
cp: target/release/libesse.a: No such file or directory
Flutter: Macos dynamic library is ok!

**Comment by sunhuachuang** [comment]
Fixed this after fork rust-web3 and upgrade the devs.

**Comment by sunhuachuang** [comment]
I will close it, if still have error, feel free to tell me.
